Controllers/PaymentTypeAnalyticsController.cs
using RailwwayDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RailwwayDB.Controllers
{
    public class PaymentTypeAnalyticsController : Controller
    {
        private railway_khanenko_ist221Entities db = new railway_khanenko_ist221Entities(); 

        // GET: PaymentTypeAnalytics
        public ActionResult PaymentTypeAnalytics()
        {
            return View();
        }

        // GET: PaymentTypeAnalytics/PaymentTypeAnalyticsData
        public JsonResult PaymentTypeAnalyticsData()
        {
            var paymentTypes = db.Payments
                                .GroupBy(p => p.type)
                                .Select(g => new { type = g.Key, count = g.Count() })
                                .ToList();

            var labels = paymentTypes.Select(pt => pt.type).ToArray();
            var data = paymentTypes.Select(pt => pt.count).ToArray();

            return Json(new { labels, data }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/PaymentTypeAnalytics/PaymentTypeAnalytics.cshtml
@{
    ViewBag.Title = "Payment Type Analytics";
}

<h2>@ViewBag.Title</h2>

<div id="paymentTypeChart" style="width: 800px; height: 600px;"></div>

@section Scripts {
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        google.charts.load('current', { packages: ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            $.ajax({
                url: '@Url.Action("PaymentTypeAnalyticsData", "PaymentTypeAnalytics")',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    var dataArray = [['Payment Type', 'Count']];

                    $.each(data.labels, function (index, label) {
                        dataArray.push([label, data.data[index]]);
                    });

                    var googleData = google.visualization.arrayToDataTable(dataArray);

                    var options = {
                        title: 'Payment Type Analytics',
                        width: 800,
                        height: 600,
                        colors: ['#757573', '#c9cecb', '#d6d8da', '#bbbbbb', '#3d3d3d']
                    };

                    var chart = new google.visualization.PieChart(document.getElementById('paymentTypeChart'));
                    chart.draw(googleData, options);
                },
                error: function (xhr, status, error) {
                    console.error(error);
                }
            });
        }
    </script>
}
